(globals
    version = 3
    io_order = default
)
(iopad
    (topright
	(inst name="PR_CORNER_NE"	cell="PCORNERR" )
    )
    (top
	(inst  name="PR_PVSS1R_top"	cell="PVSS1R" )
	(inst  name="PR_PVDD1R_top"	cell="PVDD1R" )
	(inst  name="PR_PVDD2R_top"	cell="PVDD2R" )
	(inst  name="PR_PVSS2R_top"	cell="PVSS2R" )
	(inst  name="iocell_serial_tl_0_out_bits_phit_1/cell_0"	cell="POT8R" )
	(inst  name="iocell_serial_tl_0_out_bits_phit/cell_0"	cell="POT8R" )
	(inst  name="iocell_clock_tap/cell_0"	cell="POT8R" )
	(inst  name="iocell_uart_0_txd/cell_0"	cell="POT8R" )
	(inst  name="iocell_jtag_TDO/cell_0"	cell="POT8R" )
	(inst  name="iocell_gpio_0_7/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_6/cell_0"	cell="PB8R" )
	(inst  name="iocell_jtag_TDI/cell_0"	cell="PIR" )
	(inst  name="iocell_jtag_TMS/cell_0"	cell="PIR" )
	(inst  name="iocell_jtag_reset/cell_0"	cell="PIR" )
	(inst  name="iocell_uart_0_rxd/cell_0"	cell="PIR" )
    )
    (topleft
	(inst name="PR_CORNER_NW"	cell="PCORNERR" )
    )
    (left
	(inst  name="PR_PVSS1R_left"	cell="PVSS1R" )
	(inst  name="PR_PVDD1R_left"	cell="PVDD1R" )
	(inst  name="PR_PVDD2R_left"	cell="PVDD2R" )
	(inst  name="PR_PVSS2R_left"	cell="PVSS2R" )
	(inst  name="iocell_serial_tl_0_clock_in/cell_0"	cell="PIR" )
	(inst  name="iocell_clock/cell_0"	cell="PIR" )
	(inst  name="iocell_jtag_TCK/cell_0"	cell="PIR" )
	(inst  name="iocell_custom_boot/cell_0"	cell="PIR" )
	(inst  name="iocell_reset/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_reset_in/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_in_valid/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_in_bits_phit/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_in_bits_phit_1/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_in_bits_phit_2/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_in_bits_phit_3/cell_0"	cell="PIR" )
	(inst  name="iocell_serial_tl_0_clock_out/cell_0"	cell="POT8R" )
	(inst  name="iocell_serial_tl_0_reset_out/cell_0"	cell="POT8R" )
	(inst  name="iocell_serial_tl_0_out_valid/cell_0"	cell="POT8R" )
	(inst  name="iocell_serial_tl_0_out_bits_phit_3/cell_0"	cell="POT8R" )
	(inst  name="iocell_serial_tl_0_out_bits_phit_2/cell_0"	cell="POT8R" )
    )
    (bottomleft
	(inst name="PR_CORNER_SW"	cell="PCORNERR" )
    )
    (bottom
	(inst  name="iocell_i2c_0_scl/cell_0"	cell="PB8R" )
	(inst  name="iocell_i2c_0_sda/cell_0"	cell="PB8R" )
	(inst  name="iocell_spi_0_sck/cell_0"	cell="PB8R" )
	(inst  name="iocell_spi_0_cs_0/cell_0"	cell="PB8R" )
	(inst  name="iocell_spi_0_dq_0/cell_0"	cell="PB8R" )
	(inst  name="iocell_spi_0_dq_1/cell_0"	cell="PB8R" )
	(inst  name="iocell_spi_0_dq_2/cell_0"	cell="PB8R" )
	(inst  name="PR_PVDD1R_bottom"	cell="PVDD1R" )
	(inst  name="PR_PVSS1R_bottom"	cell="PVSS1R" )
	(inst  name="PR_PVDD2R_bottom"	cell="PVDD2R" )
	(inst  name="PR_PVSS2R_bottom"	cell="PVSS2R" )
    )
    (bottomright
	(inst name="PR_CORNER_SE"	cell="PCORNERR" )
    )
    (right
	(inst  name="iocell_spi_0_dq_3/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_0/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_1/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_2/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_3/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_4/cell_0"	cell="PB8R" )
	(inst  name="iocell_gpio_0_5/cell_0"	cell="PB8R" )
	(inst  name="PR_PVDD1R_right"	cell="PVDD1R" )
	(inst  name="PR_PVSS1R_right"	cell="PVSS1R" )
	(inst  name="PR_PVDD2R_right"	cell="PVDD2R" )
	(inst  name="PR_PVSS2R_right"	cell="PVSS2R" )
    )
)
